name: "CI"

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  check:
    # Want to run this on aarch64 but https://github.com/actions/runner-images/issues/5631
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu
          components: clippy,rustfmt
      - name: Check formatting
        run: cargo fmt --all --check
      - name: Check clippy
        run: cargo clippy
      - name: test
        run: cargo test
